### ISSUE TITLE
[Question] Documentation on how to use this repo

### ISSUE THREAD

**Issue by kishikaisei** [axyl-os/axyl-i3wm#3]
This is a question for all the axyl-xxwm repos, how to use this repo? Is there some documentation for dependencies and list of packages required?
I like the configs, and how they look (tried the live session), copied them to ~/.config/xx there is some settings that got applied but not all (it threw an error about polybar which made me think about installing it).

**Comment by rubixcube199** [comment]
if you are still having issues, I can explain in the Discord Server on how to use them, they are installable packages afaik, but the is-depends is a different issue
